/**
 * The drift guard between the injected overlay and @gather/design.
 *
 * Owns: proving that src/overlay/tokens.generated.ts is still what the package
 * emits, that styles.ts writes no colour of its own, and that the pairs the
 * overlay actually draws clear WCAG AA. The overlay is the surface users of an
 * extension-first product see most, and it sits on a page nobody chose — a
 * pairing that only works on the designer's screenshot is a bug here in a way
 * it is not anywhere else.
 *
 * Deliberately NOT: an opinion on the palette. Whether `--text-low` is legible
 * across the surface ladder is packages/design/test's problem. This file asks
 * only whether the OVERLAY reads the same numbers, and whether the specific
 * combinations it composes out of them hold up.
 *
 * @gather/design is a devDependency, not a dependency: nothing under src/
 * imports it. The emitter runs here and at regen time, and the content script
 * ships the constant it produced.
 *
 * After changing packages/design/src, regenerate rather than hand-edit:
 *   pnpm --filter @gather/design build
 *   pnpm --filter @gather/extension tokens:generate
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  COLOR_TOKEN_NAMES,
  WCAG_AA_NON_TEXT,
  WCAG_AA_TEXT,
  contrastRatio,
  cssVarName,
  emitShadowRootCss,
  inkOn,
  resolveColorToken,
} from '@gather/design';
import type { ColorTokenName, FillTokenName, ThemeName } from '@gather/design';

import { OVERLAY_CSS } from '../src/overlay/styles';
import { TOKEN_CSS } from '../src/overlay/tokens.generated';

const GENERATED_PATH = fileURLToPath(
  new URL('../src/overlay/tokens.generated.ts', import.meta.url),
);
const STYLES_PATH = fileURLToPath(new URL('../src/overlay/styles.ts', import.meta.url));

/** `pnpm --filter @gather/extension tokens:generate` sets this; CI never does. */
const REGENERATE = process.env['UPDATE_TOKENS'] === '1';

const stylesSource = readFileSync(STYLES_PATH, 'utf8');

/**
 * The module wrapper around the emitted CSS. A `.ts` file rather than a `.css`
 * one because the content script needs the stylesheet as a string it can put
 * in a `<style>` inside the shadow root, and tsup would turn a CSS import into
 * a second asset the injected script cannot load.
 */
const HEADER = `/**
 * The design system's palette and scales, addressed to a shadow root.
 *
 * GENERATED by @gather/design — do not edit by hand. Change
 * packages/design/src/tokens.ts and run:
 *   pnpm --filter @gather/extension tokens:generate
 * test/design-tokens.test.ts fails for as long as this file is stale.
 *
 * Checked in rather than called at runtime: \`emitShadowRootCss()\` drags the
 * token table, the OKLCH conversions and ~6KB of string building into a content
 * script that is injected into every room tab, to arrive at a constant.
 *
 * Three states, because a CLOSED shadow root inherits nothing from the page:
 * \`:host\` carries dark, \`:host([data-theme='light'])\` is an explicit opt-in,
 * and the \`prefers-color-scheme\` block covers a host that has said neither.
 */
`;

/** Nothing the emitter produces today needs escaping; a token note could. */
const escapeTemplate = (css: string): string =>
  css.replace(/[\\`]/g, '\\$&').replace(/\$\{/g, '\\${');

const renderModule = (css: string): string =>
  `${HEADER}\nexport const TOKEN_CSS = \`${escapeTemplate(css)}\`;\n`;

/** Missing reads as empty so a deleted file fails as a diff, not as an ENOENT. */
const readGenerated = (): string =>
  existsSync(GENERATED_PATH) ? readFileSync(GENERATED_PATH, 'utf8') : '';

describe('generated token module', () => {
  it('is exactly what @gather/design emits', () => {
    const expected = renderModule(emitShadowRootCss());
    if (REGENERATE) {
      writeFileSync(GENERATED_PATH, expected, 'utf8');
    }
    expect(
      readGenerated(),
      'src/overlay/tokens.generated.ts is stale — run ' +
        '`pnpm --filter @gather/extension tokens:generate`',
    ).toBe(expected);
  });

  // Skipped only while regenerating: the module was imported before the write
  // above, so in that one run `TOKEN_CSS` is the previous file by construction.
  // The very next ordinary run is the one that checks it.
  it.skipIf(REGENERATE)('survives the round trip out of the template literal', () => {
    // The file is text on disk and a string at runtime; this is the only
    // assertion that proves the escaping between the two is lossless.
    expect(TOKEN_CSS).toBe(emitShadowRootCss());
  });

  it('declares every token three times, once per host state', () => {
    // `:host`, `:host([data-theme='light'])`, and the prefers-color-scheme
    // fallback. A closed shadow root inherits nothing, so a token missing from
    // any of the three is an unresolved var(), not a inherited page value.
    for (const token of COLOR_TOKEN_NAMES) {
      const declarations = TOKEN_CSS.split(`${cssVarName(token)}:`).length - 1;
      expect(declarations, `${cssVarName(token)} declarations`).toBe(3);
    }
  });

  it('reaches the shadow root ahead of the rules that read it', () => {
    expect(OVERLAY_CSS.startsWith(TOKEN_CSS)).toBe(true);
    expect(OVERLAY_CSS.length).toBeGreaterThan(TOKEN_CSS.length);
  });
});

describe('styles.ts holds no colour of its own', () => {
  it('writes down no hex literal and no raw colour function', () => {
    // `color-mix(in oklch, …)` is fine — it composes a token. A bare `oklch(`
    // or a hex literal is a value being written down a second time.
    expect(stylesSource).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
    expect(stylesSource).not.toMatch(/oklch\(/);
    expect(stylesSource).not.toMatch(/\brgba?\(/);
  });

  it('keeps no --gather- variable, which is what the old palette was', () => {
    expect(stylesSource).not.toMatch(/--gather-/);
  });

  it('still locks the host inline, which no stylesheet can do', () => {
    // The palette moved; the hardening did not. A page's `div { display: none }`
    // outranks any `:host` rule, so these stay inline `!important` in mount.ts.
    expect(stylesSource).toMatch(/HOST_LOCKS/);
    expect(stylesSource).toMatch(/\['pointer-events', 'none'\]/);
    expect(stylesSource).toMatch(/\['position', 'fixed'\]/);
  });
});

/**
 * A foreground, either as a palette token or as "whatever ink the package
 * measures for this fill".
 *
 * The second form exists because `.handle` and `.send` are accent FILLS, and
 * their label used to name `--bg-void` — a hand-measured answer that happened
 * to hold at 4.85:1 in light. It stopped holding the moment light `--aurora-1`
 * moved for the primary button's gradient (it fell to 4.06:1, and this guard is
 * what caught it). `--ink-on-accent` is the package computing that answer, so
 * it cannot drift out from under a palette change again.
 */
type Foreground = ColorTokenName | { readonly inkOn: FillTokenName };

interface Pairing {
  /** The rule in styles.ts this pair comes from. */
  readonly rule: string;
  readonly fg: Foreground;
  readonly bg: ColorTokenName;
  /** Non-text bar only where the token IS the affordance (the focus ring). */
  readonly bar: number;
}

const foregroundHex = (theme: ThemeName, fg: Foreground): string =>
  typeof fg === 'string' ? resolveColorToken(theme, fg).hex : inkOn(theme, fg.inkOn).hex;

const foregroundLabel = (fg: Foreground): string =>
  typeof fg === 'string' ? fg : `ink-on-${fg.inkOn}`;

/**
 * Every foreground/background the overlay composes, and the rule it comes
 * from. The panel is opaque (`--surface-1`), so these are the real pairs and
 * not an approximation of them — that is the whole reason the panel may not
 * use `--surface-glass` over an unknown page.
 */
const PAIRINGS: readonly Pairing[] = [
  {
    rule: '.panel / .room / .msg / .input / .now-title',
    fg: 'textHi',
    bg: 'surface1',
    bar: WCAG_AA_TEXT,
  },
  { rule: '.room / .person-name on .head', fg: 'textHi', bg: 'surface2', bar: WCAG_AA_TEXT },
  {
    rule: '.hide / .skip / .now-next / .ahead / .notice / .link',
    fg: 'textMid',
    bg: 'surface1',
    bar: WCAG_AA_TEXT,
  },
  { rule: '.status on .head', fg: 'textMid', bg: 'surface2', bar: WCAG_AA_TEXT },
  { rule: '.section-title', fg: 'textLow', bg: 'surface1', bar: WCAG_AA_TEXT },
  { rule: '.person-note on .person', fg: 'textLow', bg: 'surface2', bar: WCAG_AA_TEXT },
  // A 3px edge, not an author name in accent — see the rule's comment in
  // styles.ts. As a graphic the bar is 1.4.11's 3:1, and the bar it USED to be
  // held to (4.5:1, as text) is one --accent cannot meet while also being a
  // gradient stop that black sits on.
  { rule: ".msg[data-mine='true'] edge", fg: 'accent', bg: 'surface1', bar: WCAG_AA_NON_TEXT },
  { rule: '.handle / .send label', fg: { inkOn: 'accent' }, bg: 'accent', bar: WCAG_AA_TEXT },
  { rule: ':focus-visible over .panel', fg: 'focusRing', bg: 'surface1', bar: WCAG_AA_NON_TEXT },
  { rule: ':focus-visible over .head', fg: 'focusRing', bg: 'surface2', bar: WCAG_AA_NON_TEXT },
];

const THEMES: readonly ThemeName[] = ['dark', 'light'];

describe('every pair the overlay draws is legible', () => {
  for (const theme of THEMES) {
    for (const pairing of PAIRINGS) {
      it(`${theme}: ${pairing.rule} — ${foregroundLabel(pairing.fg)} on ${pairing.bg}`, () => {
        const fg = foregroundHex(theme, pairing.fg);
        const bg = resolveColorToken(theme, pairing.bg).hex;
        const ratio = contrastRatio(fg, bg);
        // The message carries the measurement, so a regression in the package
        // says how far it fell rather than only that it did.
        expect(
          ratio,
          `${foregroundLabel(pairing.fg)} (${fg}) on ${pairing.bg} (${bg}) is ${ratio.toFixed(2)}:1`,
        ).toBeGreaterThanOrEqual(pairing.bar);
      });
    }
  }

  it('would fail if the ink on the accent fill went back to --accent-ink', () => {
    // Kept as an assertion rather than a comment: --accent-ink is what
    // DESIGN.md §8 puts on a primary button, so the obvious "fix" to
    // .handle/.send is the one that breaks it. 3.80:1 in dark.
    const ink = resolveColorToken('dark', 'accentInk').hex;
    const accent = resolveColorToken('dark', 'accent').hex;
    expect(contrastRatio(ink, accent)).toBeLessThan(WCAG_AA_TEXT);
  });
});
