/**
 * The design system's palette and scales, addressed to a shadow root.
 *
 * GENERATED by @gather/design — do not edit by hand. Change
 * packages/design/src/tokens.ts and run:
 *   pnpm --filter @gather/extension tokens:generate
 * test/design-tokens.test.ts fails for as long as this file is stale.
 *
 * Checked in rather than called at runtime: `emitShadowRootCss()` drags the
 * token table, the OKLCH conversions and ~6KB of string building into a content
 * script that is injected into every room tab, to arrive at a constant.
 *
 * Three states, because a CLOSED shadow root inherits nothing from the page:
 * `:host` carries dark, `:host([data-theme='light'])` is an explicit opt-in,
 * and the `prefers-color-scheme` block covers a host that has said neither.
 */

export const TOKEN_CSS = `/* Generated by @gather/design — do not edit by hand. Change packages/design/src/tokens.ts. */

:host {
  --bg-void:        oklch(0.115 0.006 265);  /* cinema black */
  --bg-deep:        oklch(0.16 0.008 265);
  /* glass panels also carry blur(16px) saturate(1.08) */
  --surface-glass:  oklch(1 0 0 / 0.06);
  --surface-raised: oklch(1 0 0 / 0.09);
  --border-glass:   oklch(1 0 0 / 0.1);
  --surface-0:      var(--bg-void);  /* page ground */
  --surface-1:      oklch(0.205 0.009 265);  /* rail, cards */
  --surface-2:      oklch(0.245 0.01 265);  /* hover, raised card */
  /* active / selected row. --text-low holds 4.56:1 here and falls under AA above ~0.28 */
  --surface-3:      oklch(0.275 0.011 265);
  --hairline:       oklch(1 0 0 / 0.07);
  --scrim:          oklch(0.05 0.008 265 / 0.72);
  --text-hi:        oklch(0.97 0.005 285);
  --text-mid:       oklch(0.78 0.015 285);
  /* measured floor: 0.58 fell to 3.53:1 on --surface-3; 0.65 holds >=4.56:1 across the ladder */
  --text-low:       oklch(0.65 0.02 285);
  --aurora-1:       oklch(0.62 0.22 292);  /* electric violet */
  --aurora-2:       oklch(0.65 0.215 328);  /* magenta */
  --aurora-3:       oklch(0.7 0.17 356);  /* warm rose */
  /* listen rooms rebind this to the artwork colour at runtime */
  --accent:         var(--aurora-1);
  --accent-ink:     oklch(0.98 0.01 295);  /* ink on aurora gradients */
  --success:        oklch(0.75 0.17 160);
  --danger:         oklch(0.68 0.21 25);
  --warn:           oklch(0.82 0.16 85);
  --focus-ring:     oklch(0.72 0.2 292);

  /* ink on a filled control — absolute, chosen per fill, never per theme */
  --ink-black:              oklch(0 0 0);
  --ink-white:              oklch(1 0 0);
  --ink-on-aurora-1:        var(--ink-black);
  --ink-on-aurora-2:        var(--ink-black);
  --ink-on-aurora-3:        var(--ink-black);
  --ink-on-accent:          var(--ink-black);
  --ink-on-success:         var(--ink-black);
  --ink-on-danger:          var(--ink-black);
  --ink-on-warn:            var(--ink-black);
  /* a label crossing all three aurora stops takes one ink */
  --ink-on-aurora-gradient: var(--ink-black);

  --space-xs:               4px;
  --space-sm:               8px;
  --space-md:               12px;
  --space-lg:               16px;
  --space-xl:               24px;
  --space-xxl:              32px;
  --space-xxxl:             48px;
  --space-section:          64px;
  --space-chapter:          96px;
  --space-canvas:           128px;
  --radius-sm:              6px;
  --radius-control:         8px;
  --radius-card:            14px;
  --radius-panel:           20px;
  --radius-stage:           28px;
  --radius-pill:            999px;
  --layout-edge:            3px;
  --layout-tap:             44px;
  --layout-row:             56px;
  --layout-rail:            380px;
  --layout-tabBar:          48px;
  --text-hero-size:         40px;
  --text-hero-line:         1.04;
  --text-hero-weight:       700;
  --text-hero-tracking:     -0.045em;
  --text-display-size:      44px;
  --text-display-line:      48px;
  --text-display-weight:    600;
  --text-display-tracking:  -0.035em;
  --text-headline-size:     28px;
  --text-headline-line:     34px;
  --text-headline-weight:   600;
  --text-headline-tracking: -0.025em;
  --text-title-size:        20px;
  --text-title-line:        28px;
  --text-title-weight:      600;
  --text-title-tracking:    -0.01em;
  --text-body-size:         16px;
  --text-body-line:         26px;
  --text-body-weight:       400;
  --text-body-tracking:     0;
  --text-label-size:        13px;
  --text-label-line:        18px;
  --text-label-weight:      500;
  --text-label-tracking:    0;
  --text-caption-size:      11px;
  --text-caption-line:      14px;
  --text-caption-weight:    500;
  --text-caption-tracking:  0.08em;
  --elevation-e1:           0 0 0 1px var(--hairline), 0 2px 8px -3px color-mix(in oklch, var(--ink-black) 16%, transparent);
  --elevation-e2:           0 0 0 1px var(--hairline), 0 10px 30px -8px color-mix(in oklch, var(--ink-black) 24%, transparent);
  --elevation-e3:           0 0 0 1px var(--hairline), 0 24px 64px -16px color-mix(in oklch, var(--ink-black) 30%, transparent);
  --dur-micro:              220ms;
  --dur-panel:              300ms;
  --dur-max:                400ms;
  --dur-reduced:            150ms;
  --ease-spring:            cubic-bezier(0.34, 1.3, 0.64, 1);
  --font-display:           'Space Grotesk', system-ui, sans-serif;
  --font-sans:              Inter, system-ui, sans-serif;
  --font-mono:              'JetBrains Mono', ui-monospace, monospace;
  --grain:                  url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='160' height='160'%3E%3Cfilter id='g'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.8' numOctaves='3' stitchTiles='stitch'/%3E%3CfeColorMatrix type='saturate' values='0'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23g)' opacity='0.035'/%3E%3C/svg%3E");
  --grain-size:             160px 160px;
}

:host {
  /* Desktop density. The coarse-pointer block below is the touch answer. */
  --control-h-sm:   28px;
  --control-px-sm:  10px;
  --control-gap-sm: 6px;
  --control-h-md:   32px;
  --control-px-md:  12px;
  --control-gap-md: 8px;
  --control-h-lg:   40px;
  --control-px-lg:  20px;
  --control-gap-lg: 8px;
}

@media (pointer: coarse) {
  /* A finger, not a mouse: every control goes back to a 44px target. */
  :host {
    --control-h-sm: 44px;
    --control-h-md: 44px;
    --control-h-lg: 48px;
  }
}

:host([data-theme='light']) {
  --bg-void:        oklch(0.965 0.004 265);
  --bg-deep:        oklch(0.925 0.006 265);
  --surface-glass:  oklch(1 0 0 / 0.7);
  --surface-raised: oklch(1 0 0 / 0.85);
  --border-glass:   oklch(0.28 0.012 265 / 0.16);
  --surface-0:      var(--bg-void);  /* page ground */
  --surface-1:      oklch(0.995 0.002 265);  /* rail, cards */
  --surface-2:      oklch(0.95 0.005 265);  /* hover, raised card */
  /* active / selected row; the rung --accent is measured on */
  --surface-3:      oklch(0.91 0.008 265);
  --hairline:       oklch(0.28 0.012 265 / 0.14);
  /* same wash as dark — the brightest pixel behind it is the same */
  --scrim:          oklch(0.05 0.008 265 / 0.72);
  --text-hi:        oklch(0.22 0.012 265);
  --text-mid:       oklch(0.42 0.014 265);
  /* measured floor: 0.55 fell to 3.83:1 on --surface-3; 0.49 holds >=4.82:1 across the ladder */
  --text-low:       oklch(0.49 0.014 265);
  --aurora-1:       oklch(0.585 0.175 292);  /* electric violet */
  --aurora-2:       oklch(0.615 0.175 328);  /* magenta */
  --aurora-3:       oklch(0.655 0.145 356);  /* warm rose */
  /* listen rooms rebind this to the artwork colour at runtime */
  --accent:         var(--aurora-1);
  --accent-ink:     oklch(0.98 0.01 295);  /* ink on aurora gradients */
  --success:        oklch(0.55 0.15 160);
  --danger:         oklch(0.55 0.19 25);
  /* measured floor: 0.62 fell to 2.88:1 on --surface-3, under the 3:1 non-text bar; 0.58 holds >=3.33:1 */
  --warn:           oklch(0.58 0.14 85);
  --focus-ring:     oklch(0.58 0.18 292);

  /* ink on a filled control — absolute, chosen per fill, never per theme */
  --ink-black:              oklch(0 0 0);
  --ink-white:              oklch(1 0 0);
  --ink-on-aurora-1:        var(--ink-black);
  --ink-on-aurora-2:        var(--ink-black);
  --ink-on-aurora-3:        var(--ink-black);
  --ink-on-accent:          var(--ink-black);
  --ink-on-success:         var(--ink-black);
  --ink-on-danger:          var(--ink-white);
  --ink-on-warn:            var(--ink-black);
  /* a label crossing all three aurora stops takes one ink */
  --ink-on-aurora-gradient: var(--ink-black);
}

@media (prefers-color-scheme: light) {
  :host(:not([data-theme='dark'])) {
    --bg-void:        oklch(0.965 0.004 265);
    --bg-deep:        oklch(0.925 0.006 265);
    --surface-glass:  oklch(1 0 0 / 0.7);
    --surface-raised: oklch(1 0 0 / 0.85);
    --border-glass:   oklch(0.28 0.012 265 / 0.16);
    --surface-0:      var(--bg-void);  /* page ground */
    --surface-1:      oklch(0.995 0.002 265);  /* rail, cards */
    --surface-2:      oklch(0.95 0.005 265);  /* hover, raised card */
    /* active / selected row; the rung --accent is measured on */
    --surface-3:      oklch(0.91 0.008 265);
    --hairline:       oklch(0.28 0.012 265 / 0.14);
    /* same wash as dark — the brightest pixel behind it is the same */
    --scrim:          oklch(0.05 0.008 265 / 0.72);
    --text-hi:        oklch(0.22 0.012 265);
    --text-mid:       oklch(0.42 0.014 265);
    /* measured floor: 0.55 fell to 3.83:1 on --surface-3; 0.49 holds >=4.82:1 across the ladder */
    --text-low:       oklch(0.49 0.014 265);
    --aurora-1:       oklch(0.585 0.175 292);  /* electric violet */
    --aurora-2:       oklch(0.615 0.175 328);  /* magenta */
    --aurora-3:       oklch(0.655 0.145 356);  /* warm rose */
    /* listen rooms rebind this to the artwork colour at runtime */
    --accent:         var(--aurora-1);
    --accent-ink:     oklch(0.98 0.01 295);  /* ink on aurora gradients */
    --success:        oklch(0.55 0.15 160);
    --danger:         oklch(0.55 0.19 25);
    /* measured floor: 0.62 fell to 2.88:1 on --surface-3, under the 3:1 non-text bar; 0.58 holds >=3.33:1 */
    --warn:           oklch(0.58 0.14 85);
    --focus-ring:     oklch(0.58 0.18 292);

    /* ink on a filled control — absolute, chosen per fill, never per theme */
    --ink-black:              oklch(0 0 0);
    --ink-white:              oklch(1 0 0);
    --ink-on-aurora-1:        var(--ink-black);
    --ink-on-aurora-2:        var(--ink-black);
    --ink-on-aurora-3:        var(--ink-black);
    --ink-on-accent:          var(--ink-black);
    --ink-on-success:         var(--ink-black);
    --ink-on-danger:          var(--ink-white);
    --ink-on-warn:            var(--ink-black);
    /* a label crossing all three aurora stops takes one ink */
    --ink-on-aurora-gradient: var(--ink-black);
  }
}
`;
