/**
 * Mesh manager: owns one RTCPeerConnection per remote peer, drives perfect
 * negotiation over the room websocket, attaches the typed DataChannel fabric,
 * and fans local media tracks out to every current and future connection.
 *
 * Everything here is event-driven and defensive — a misbehaving peer, a stale
 * signal, or a throwing platform primitive must surface through `onError`,
 * never as an exception escaping an event path.
 */

import type { PresenceEntry, RoomId, UserId } from '@gather/contracts';
import { applyMaxBitrate, clearMaxBitrate } from './adaptation';
import { CHANNEL_IDS, ChannelFabric } from './channels';
import type { ChannelFabricOptions, ChannelLabel } from './channels';
import { classifyLinkStats } from './linkstate';
import type { MeshLinkState } from './linkstate';
import { PerfectNegotiator } from './negotiation';
import { TRACK_ROLES } from './types';
import type {
  ClearTimeoutFn,
  ConnectionStateLike,
  DataChannelLike,
  IceServerLike,
  InboundSignal,
  MediaStreamFactory,
  MediaStreamLike,
  MediaStreamTrackLike,
  NowFn,
  RtcConfigLike,
  RtcFactory,
  RtcPeerConnectionLike,
  RtpSenderLike,
  SetTimeoutFn,
  SignalSend,
  TimeoutHandle,
  TrackRole,
} from './types';

/** Per-peer connection state exposed to subscribers. */
export type MeshConnectionState = ConnectionStateLike;

/**
 * The fixed vocabulary of AUXILIARY meshes one identity may run alongside its
 * primary one.
 *
 * A person sharing from the extension is in the room twice: the web tab holds
 * the call, the offscreen document holds the screen capture, and both
 * authenticate as the same user — correctly, because the server stamps
 * `fromUserId` from the socket. The pair-derived connectionId then came out
 * IDENTICAL for both, so a viewer answered whichever spoke first and dropped
 * the other as a stale/glare-loser answer: about half the time it landed on
 * the call connection and never saw the share, the other half on the share
 * connection and never heard the voice.
 *
 * A lane names WHICH of that identity's meshes a connection belongs to, and it
 * is folded into the connectionId, so the two can no longer collide.
 *
 * The vocabulary is deliberately fixed and tiny rather than free-form: a lane
 * has to be guessable in advance, because an auxiliary endpoint is never
 * dialled and so never gets to announce itself before it offers. Endpoints
 * that ARE dialled use `endpointId` instead (see {@link MeshManagerOptions}),
 * which needs no vocabulary at all.
 */
export const MESH_LANES = ['share'] as const;

/** One of {@link MESH_LANES}. */
export type MeshLane = (typeof MESH_LANES)[number];

/**
 * How many ENDPOINTS of one identity this mesh will hold connections to.
 *
 * The old lane vocabulary bounded this structurally (lanes + 1). Announced
 * endpoint tokens are free-form, so the bound has to be explicit: without one,
 * a peer that announced tokens in a loop could make every other client in the
 * room build peer connections until the tab died. Four covers the honest
 * cases — laptop + phone + a reloaded tab still holding a slot + a share.
 */
const MAX_ENDPOINTS_PER_USER = 4;

/** What an announced endpoint token may look like. It is generated by the
 *  remote, so it is validated before it is ever concatenated into an id: a
 *  token carrying ':' or '~' could otherwise forge an id belonging to another
 *  pair. Length is bounded for the same reason ids are compared, not parsed. */
const ENDPOINT_TOKEN_RE = /^[A-Za-z0-9_-]{1,64}$/;

/**
 * How many stream-id→role announcements this mesh remembers per identity.
 *
 * One endpoint has at most one stream per role, and an identity holds at most
 * {@link MAX_ENDPOINTS_PER_USER} endpoints, so this is the honest ceiling for a
 * well-behaved peer. It is a ceiling rather than an assumption because the
 * announcements are remote-generated: without one, a peer announcing in a loop
 * would grow this map until the tab died.
 */
const MAX_ROLE_STREAMS_PER_USER = MAX_ENDPOINTS_PER_USER * TRACK_ROLES.length;

/** What an announced STREAM id may look like. Browsers mint a UUID (Chrome,
 *  Safari) or a brace-wrapped one (older Firefox); the bound is what matters,
 *  because the id is remote-generated. It is only ever COMPARED — never
 *  concatenated into an id — so nothing in it can forge structure, and an id
 *  this rejects simply goes unannounced and is answered `null` downstream. */
const STREAM_ID_RE = /^[A-Za-z0-9_{}.-]{1,64}$/;

/** Options for {@link MeshManager}. */
export interface MeshManagerOptions {
  roomId: RoomId;
  localUserId: UserId;
  /**
   * Which of this identity's meshes this one is.
   *
   * Omitted — the default, and what every web/mobile client wants — makes it
   * the PRIMARY mesh: the one presence dials, the one that carries the call
   * and the DataChannel fabric, and the only one that will answer a remote
   * auxiliary endpoint.
   *
   * Set it only on a SECOND mesh the same user runs at the same time (today:
   * the extension's offscreen share document). An auxiliary mesh reaches
   * remote PRIMARY meshes only, and only by offering first — it is a one-way
   * media pipe, so it never needs a peer to dial IT, which is exactly why its
   * lane does not have to be discoverable in advance.
   */
  lane?: MeshLane;
  /**
   * This mesh INSTANCE's own identity — a token the client generates once per
   * mesh, distinct from the account on every one of its devices and tabs.
   *
   * A UserId names a person, and one person is routinely in a room from two
   * places at once (laptop and phone, or two tabs). Both used to derive the
   * same connectionId for a given remote, so the remote held ONE peer
   * connection for the pair: each side's offer re-applied over the other's,
   * restarting ICE and DTLS, and the call flipped between the two devices for
   * as long as both stayed open. An endpoint token is what makes the two
   * addressable apart.
   *
   * Omitting it keeps this mesh on the person-level id every build has always
   * derived — which is what a second mesh of the SAME identity (the extension's
   * offscreen share, addressed by `lane`) wants, and what keeps a client that
   * predates endpoint tokens reachable.
   *
   * The token is announced to each peer over the signalling channel (see
   * `announceTo`), because presence carries no per-socket field to put it in.
   */
  endpointId?: string;
  /** Injected platform peer-connection factory. */
  rtcFactory: RtcFactory;
  /**
   * Injected platform MediaStream factory (`() => new MediaStream()` on web).
   *
   * Supplying it is what lets a RECEIVER name the role of a remote track. Each
   * local role gets one stream, its id is announced to every peer, and its
   * tracks are published with `addTrack(track, stream)` so the id reaches the
   * far side on `ev.streams`. Without it — the default — tracks are published
   * bare, nothing is announced, and every receiver answers `null`, which is
   * exactly what a client that predates this must be answered anyway.
   */
  mediaStreamFactory?: MediaStreamFactory;
  /** Outbound signaling transport (room WS). */
  send: SignalSend;
  /** Fresh ICE servers spliced into every NEW RTCPeerConnection
   *  (typically TurnCredentialManager.iceServers). Callers normally start that
   *  fetch without awaiting it, so this may legitimately return [] for the
   *  first few hundred ms of a room; see `fallbackIceServers`. */
  getIceServers?: () => IceServerLike[];
  /** Used INSTEAD of an empty getIceServers() result, and repaired away once
   *  real credentials show up. Defaults to public STUN. Pass [] to opt out and
   *  keep building peers with no ICE servers at all. */
  fallbackIceServers?: IceServerLike[];
  now: NowFn;
  setTimeoutFn: SetTimeoutFn;
  clearTimeoutFn: ClearTimeoutFn;
  /** Gap before an unanswered offer is re-sent (see {@link PerfectNegotiator}). */
  offerRetryMs?: number;
  /** Per-link stats poll implementation; defaults to pc.getStats?.(). */
  statsPollFn?: (pc: RtcPeerConnectionLike) => Promise<unknown>;
  /** Operator cost lever, off by default: no caller sets it, so every share
   *  runs at full quality. When set, the 'share' sender on any RELAYED link is
   *  bitrate-capped to this many kbps (maxBitrate on every encoding), and
   *  uncapped again when the link becomes 'direct'. Audio is never capped —
   *  not the microphone, and not the share's own soundtrack ('share-audio'),
   *  which is the half of a share people notice going missing. A share to a
   *  peer whose link has not been classified yet — a
   *  brand-new connection — runs uncapped for up to one pollStats interval,
   *  until the first poll classifies the link; a share started on an existing
   *  relayed link is capped from the first frame. */
  capRelayedVideoKbps?: number;
  /**
   * Ceiling for the CAMERA, in kbps, on every link — direct or relayed.
   *
   * A mesh sends one encode per receiver, so the camera is the one role whose
   * cost multiplies with the room: at 720p/2.5 Mbps, four receivers is 10 Mbps
   * of uplink from a laptop on hotel wifi, and the failure is not a worse
   * picture but a call that stops working. The configured value is the ceiling
   * for a SINGLE receiver and is divided among them (floored at
   * {@link MIN_CAM_KBPS}), so the total stays roughly flat as people join.
   *
   * Unset (the default) leaves the camera uncapped, which is what every caller
   * that only ever shares a screen wants. Audio is never capped.
   */
  capCamKbps?: number;
  /** Negotiation errors etc. surface here. */
  onError?: (peerId: UserId, context: string, err: unknown) => void;
  fabricOptions?: ChannelFabricOptions;
}

/** One remote endpoint this mesh knows how to address. A person is one
 *  identity and, these days, several of these. */
interface RemoteEndpoint {
  /** How the far side names ITSELF inside a connectionId. */
  name: string;
  /** Its lane; null when it is that person's primary (dialled) mesh. */
  lane: MeshLane | null;
  /** It announced an endpoint token, so the id pairs our token-bearing name
   *  with its own. False for the person-level name every build derives. */
  announced: boolean;
}

/** Everything the mesh keeps per remote ENDPOINT. One remote identity may hold
 *  more than one: their call and their share are two of these, and so are the
 *  same person's laptop and phone. */
interface MeshPeer {
  pc: RtcPeerConnectionLike;
  negotiator: PerfectNegotiator;
  senders: Map<TrackRole, RtpSenderLike>;
  state: MeshConnectionState;
  connectionId: string;
  /** The remote identity. Several endpoints may share one. */
  userId: UserId;
  /** How the far end names itself; unique per endpoint of that identity. */
  name: string;
  /** The remote endpoint's lane; null when it is that user's primary mesh. */
  lane: MeshLane | null;
  /** Whether this link is addressed by endpoint token rather than by person. */
  announced: boolean;
  /** The fabric channels this link created, whether or not it owns the fabric
   *  for its person (see `fabricOwner`). Held so the fabric can move to a
   *  surviving endpoint when the owner goes away. */
  channels: Map<ChannelLabel, DataChannelLike>;
  /** Whether the fabric for this PERSON currently runs over this link. */
  fabricOwner: boolean;
  /** Last REPORTED link path (post-debounce), not the raw last classification. */
  linkState: MeshLinkState;
  /** Consecutive 'unknown' classifications while linkState is known. */
  unknownStreak: number;
  /** Bitrate ceilings THIS mesh pushed onto a sender, in bps, per role. Any
   *  other value on the sender belongs to another writer and is left alone. */
  caps: Map<TrackRole, number>;
  /** Pending 'failed'/'disconnected' recovery attempt, if any. */
  recoveryTimer: TimeoutHandle | null;
  /** ICE restarts spent on the current outage; reset by a connect. */
  iceRestarts: number;
  /** The restart budget ran out and the link was reported dead for good. */
  recoveryExhausted: boolean;
  /** Built on the fallback ICE list because getIceServers() was still empty.
   *  Repaired (and cleared) as soon as real credentials appear. */
  iceProvisional: boolean;
}

/** The fixed channel labels created pre-negotiated on every connection. */
const FABRIC_LABELS: readonly ChannelLabel[] = ['sync', 'file'];

/** A known link state only demotes to 'unknown' after this many consecutive
 *  unknown classifications — stats gaps during ICE restarts are transient and
 *  must not flap the reported state (or the user-facing copy) every poll. */
const UNKNOWN_POLLS_TO_DEMOTE = 2;

/** Stand-in for credentials that have not arrived — or never will. A peer
 *  built with NO ice servers can only ever offer host candidates, so it fails
 *  for everyone off the local network, permanently: WebRTC does not re-read
 *  the configuration of a live connection. Public STUN is the smallest thing
 *  that keeps such a peer usable. */
const DEFAULT_FALLBACK_ICE_SERVERS: IceServerLike[] = [
  { urls: ['stun:stun.l.google.com:19302', 'stun:stun1.l.google.com:19302'] },
];

/** How often a mesh holding provisional peers re-reads getIceServers(). */
const ICE_REPAIR_POLL_MS = 250;

/** How long that re-read keeps going before the fallback is accepted as final.
 *  Long enough to cover the credential manager's first couple of retries. */
const ICE_REPAIR_WINDOW_MS = 30_000;

/** Roles the publish audience gates. A camera and a microphone are the CALL,
 *  and a call has members — a room does not. Screen share deliberately stays
 *  room-wide: watching a share is not joining a call, and Mode B viewers who
 *  never pressed Join are most of its audience. */
const AUDIENCE_ROLES: readonly TrackRole[] = ['cam', 'mic'];

/** Floor for the divided camera ceiling: below this the picture is worth less
 *  than the bytes, and the answer is to stop sending video, not to send an
 *  unwatchable slideshow of it. */
const MIN_CAM_KBPS = 120;

/** How long a link may sit in 'disconnected' before recovery treats it as
 *  broken. ICE reports 'disconnected' for ordinary things — a wifi roam, a
 *  handful of lost consent checks — and most of them heal on their own inside
 *  a couple of seconds; restarting on sight of it would churn every link in a
 *  lossy room. Waiting forever is the bug this exists to fix. */
const DISCONNECT_GRACE_MS = 8000;

/** ICE restarts spent on one outage before the link is declared dead.
 *  Unbounded restarts against a path that is genuinely gone are indisting-
 *  uishable from a working recovery from the outside: the tile says "trying to
 *  get it back" forever and nobody is ever told to reload. */
const ICE_RESTART_LIMIT = 4;

/** Backoff between restart attempts. The first is immediate — most failures
 *  are a NAT rebinding away from working — and the rest give the far side and
 *  the network time to come back before spending another gathering round. */
const ICE_RESTART_BACKOFF_MS = [0, 2000, 6000, 15_000];

/** How long a peer that presence took away is refused re-admission by an
 *  inbound signal. Long enough to swallow the signals already in flight behind
 *  the departure, short enough that a peer who is genuinely still there — our
 *  presence being the thing that is wrong — gets back in on its next re-offer
 *  instead of being locked out until presence recovers. */
const ADMIT_SUPPRESS_MS = 5000;

/** How usable each connection state is. When one identity holds several
 *  endpoints, the best of them stands for the person: the app's question is
 *  "can I reach them", and one live link answers yes. It also keeps 'closed'
 *  meaning what the app relies on it meaning — nothing of theirs is left — so
 *  a share ending cannot make a caller drop the tracks of the call. */
const STATE_RANK: Record<MeshConnectionState, number> = {
  connected: 5,
  connecting: 4,
  new: 3,
  disconnected: 2,
  failed: 1,
  closed: 0,
};

/** The optional live-reconfiguration method: present on browser and
 *  react-native RTCPeerConnection, absent from RtcPeerConnectionLike because
 *  not every injected primitive has to provide it. Probed structurally. */
type Reconfigurable = { setConfiguration?: (config: RtcConfigLike) => void };

/** Map key for one remote endpoint. The endpoint NAME leads and is separated
 *  by a NUL: a UserId is only constrained to be a non-empty string, so a user
 *  could in principle be named `bob/share` and collide with bob's share
 *  endpoint in any printable-separator scheme. Nothing puts a NUL in an id. */
function peerKey(userId: UserId, name: string): string {
  return `${name}\u0000${userId}`;
}

/** How an endpoint names itself INSIDE a connectionId. An unlaned endpoint
 *  with no token is its bare user id, so a room where nobody runs a second
 *  mesh and nobody announces a token derives exactly the ids it always did —
 *  which is what keeps a build that predates endpoint tokens reachable from
 *  one that has them. */
function endpointName(userId: UserId, lane: MeshLane | null, token: string | null): string {
  const laned = lane === null ? `${userId}` : `${userId}/${lane}`;
  return token === null ? laned : `${laned}#${token}`;
}

/** The id of a platform MediaStream handed to us as `unknown`. `ev.streams` is
 *  whatever the platform put there and this package types none of it, so the
 *  one field it reads is probed structurally. */
function streamIdOf(stream: unknown): string | null {
  if (typeof stream !== 'object' || stream === null) return null;
  const id = (stream as { id?: unknown }).id;
  return typeof id === 'string' ? id : null;
}

/** Fold one endpoint's link path into the answer for the whole person.
 *  Conservative about cost — any relayed endpoint makes the person relayed,
 *  because that is the one that spends TURN egress — and optimistic about
 *  classification, so an endpoint no poll has reached yet does not erase what
 *  another one already established. */
function foldLink(seen: MeshLinkState | undefined, next: MeshLinkState): MeshLinkState {
  if (seen === undefined) return next;
  if (seen === 'relayed' || next === 'relayed') return 'relayed';
  if (seen === 'direct' || next === 'direct') return 'direct';
  return 'unknown';
}

/**
 * Owns the full-mesh lifecycle: reconcile the desired peer set, route
 * signaling, manage local track publication, and expose remote tracks,
 * per-peer states, and link stats to the app layer.
 */
export class MeshManager {
  /** The typed DataChannel fabric shared by beacon/fileshare/emote layers. */
  readonly fabric: ChannelFabric;

  private readonly roomId: RoomId;
  private readonly localUserId: UserId;
  private readonly lane: MeshLane | null;
  /** This mesh instance's own token, or null when it runs person-level. */
  private readonly endpointId: string | null;
  /** How THIS endpoint names itself to a remote that announced a token. */
  private readonly localName: string;
  /** How THIS endpoint names itself to everyone else — the person-level name
   *  every build derives, token or no token. */
  private readonly localBareName: string;
  private readonly rtcFactory: RtcFactory;
  private readonly mediaStreamFactory: MediaStreamFactory | undefined;
  private readonly send: SignalSend;
  private readonly getIceServers: () => IceServerLike[];
  /** False when the caller supplied no getIceServers at all: there is then no
   *  pending fetch to wait on, so nothing is ever provisional. */
  private readonly iceServersProvided: boolean;
  private readonly fallbackIceServers: IceServerLike[];
  private readonly now: NowFn;
  private readonly setTimeoutFn: SetTimeoutFn;
  private readonly clearTimeoutFn: ClearTimeoutFn;
  private readonly offerRetryMs: number | undefined;
  private readonly statsPollFn: ((pc: RtcPeerConnectionLike) => Promise<unknown>) | undefined;
  private readonly capRelayedVideoKbps: number | undefined;
  private readonly capCamKbps: number | undefined;
  private readonly onError: (peerId: UserId, context: string, err: unknown) => void;

  /** Every remote ENDPOINT, keyed by {@link peerKey}. One identity can hold
   *  several: their call and their share are two connections. */
  private readonly peerMap = new Map<string, MeshPeer>();
  /** Last state announced per USER, so a person with two endpoints produces
   *  one stream of events rather than two interleaved ones. */
  private readonly reportedStates = new Map<UserId, MeshConnectionState>();
  private readonly reportedLinks = new Map<UserId, MeshLinkState>();
  /** Peers an explicit reconcile took away, and the moment they may be admitted
   *  by signal again. Presence is authoritative about who LEFT, so the signals
   *  still in flight behind a departure must not resurrect the peer. Keyed by
   *  USER: a person presence took away takes every endpoint of theirs with them. */
  private readonly admitSuppressedUntil = new Map<UserId, number>();
  /** People presence named. We dial these and nobody else; an admitted peer is
   *  held but never re-dialled, so a stranger cannot make us reconnect to them. */
  private readonly dialed = new Set<UserId>();
  /** Endpoint tokens each identity has announced, in announcement order, with
   *  the lane each one runs. Bounded by MAX_ENDPOINTS_PER_USER. */
  private readonly announced = new Map<UserId, Map<string, MeshLane | null>>();
  /** Identities we address per ENDPOINT. Entering this set is one-way for the
   *  life of the peer: it is what stops a second tab of theirs falling back
   *  onto the person-level id and stealing the link this one holds. */
  private readonly perEndpoint = new Set<UserId>();
  /** Identities we have already told our own endpoint token. */
  private readonly announcedTo = new Set<UserId>();
  /** The stream each LOCAL role publishes on, minted on first use. A cached
   *  null is "the factory could not give us a usable one" — that role then
   *  publishes bare, forever, rather than re-minting on every addTrack. */
  private readonly roleStreams = new Map<TrackRole, MediaStreamLike | null>();
  /** Which of our role streams each identity has been told about. */
  private readonly roleAnnouncedTo = new Map<UserId, Set<TrackRole>>();
  /** Stream-id→role, PER REMOTE IDENTITY. Per-identity is what keeps one
   *  peer's announcements off another peer's tracks: `fromUserId` is stamped
   *  by the server from the authenticated socket, so it cannot be claimed. */
  private readonly announcedRoles = new Map<UserId, Map<string, TrackRole>>();
  /** Whom the CALL roles may be published to, or null for "everyone we are
   *  connected to" — the default, and what a share-only mesh wants. */
  private publishAudience: Set<UserId> | null = null;
  private iceRepairTimer: TimeoutHandle | null = null;
  private iceRepairDeadline = 0;
  private readonly localTracks = new Map<TrackRole, MediaStreamTrackLike>();
  private readonly trackSubs = new Set<
    (
      peerId: UserId,
      track: MediaStreamTrackLike,
      streams: unknown[],
      role: TrackRole | null,
    ) => void
  >();
  private readonly stateSubs = new Set<(peerId: UserId, state: MeshConnectionState) => void>();
  private readonly linkSubs = new Set<(peerId: UserId, state: MeshLinkState) => void>();
  private closed = false;

  constructor(opts: MeshManagerOptions) {
    this.roomId = opts.roomId;
    this.localUserId = opts.localUserId;
    this.lane = opts.lane ?? null;
    // A token that would not survive the round trip intact is no token at all:
    // taking it silently would derive ids the far side cannot match.
    this.endpointId =
      opts.endpointId !== undefined && ENDPOINT_TOKEN_RE.test(opts.endpointId)
        ? opts.endpointId
        : null;
    this.localBareName = endpointName(opts.localUserId, this.lane, null);
    this.localName = endpointName(opts.localUserId, this.lane, this.endpointId);
    this.rtcFactory = opts.rtcFactory;
    this.mediaStreamFactory = opts.mediaStreamFactory;
    this.send = opts.send;
    this.getIceServers = opts.getIceServers ?? (() => []);
    this.iceServersProvided = opts.getIceServers !== undefined;
    this.fallbackIceServers = opts.fallbackIceServers ?? DEFAULT_FALLBACK_ICE_SERVERS;
    this.now = opts.now;
    this.setTimeoutFn = opts.setTimeoutFn;
    this.clearTimeoutFn = opts.clearTimeoutFn;
    this.offerRetryMs = opts.offerRetryMs;
    this.statsPollFn = opts.statsPollFn;
    this.capRelayedVideoKbps = opts.capRelayedVideoKbps;
    this.capCamKbps = opts.capCamKbps;
    this.onError = opts.onError ?? (() => {});
    this.fabric = new ChannelFabric(opts.fabricOptions);
  }

  /** Reconcile toward the desired remote-peer set (adds + removes).
   *
   *  Presence names PEOPLE, and each person may be here from more than one
   *  place: whichever of their endpoints have announced themselves are dialled
   *  individually, and a person who has announced nothing is dialled once, by
   *  the person-level name every build derives. An auxiliary endpoint is never
   *  dialled at all — it announces itself by offering (see {@link
   *  handleSignal}). A departure still takes every endpoint of that person with
   *  it: presence is authoritative about who left, whatever they had open. */
  syncPeers(userIds: UserId[]): void {
    if (this.closed) return;
    const desired = new Set(userIds);
    for (const peerId of desired) {
      if (peerId === this.localUserId) continue;
      this.admitSuppressedUntil.delete(peerId);
      this.dialed.add(peerId);
      // Tell them which endpoint we are before they answer us, so the id they
      // answer on is already the per-endpoint one when they hold two of us.
      this.announceTo(peerId);
      this.announceRolesTo(peerId);
      this.reconcileEndpoints(peerId);
    }
    for (const [key, peer] of [...this.peerMap]) {
      if (desired.has(peer.userId)) continue;
      // Note the departure: signals from this peer may still be in flight
      // behind the presence update, and they must not re-open the connection.
      this.admitSuppressedUntil.set(peer.userId, this.now() + ADMIT_SUPPRESS_MS);
      this.removePeer(key);
    }
    for (const userId of [...this.dialed]) {
      if (desired.has(userId)) continue;
      // Everything learned about a person who left goes with them: their
      // endpoint tokens are per-socket, and the ones they come back with will
      // be new. Keeping the old ones would spend their connection budget on
      // sockets that no longer exist.
      this.dialed.delete(userId);
      this.announced.delete(userId);
      this.announcedTo.delete(userId);
      this.perEndpoint.delete(userId);
      this.announcedRoles.delete(userId);
      this.roleAnnouncedTo.delete(userId);
    }
  }

  /** Convenience: derive the desired set from presence entries — everyone who is
   *  not the local user and not 'offline'. */
  applyPresence(entries: PresenceEntry[]): void {
    this.syncPeers(
      entries
        .filter((e) => e.userId !== this.localUserId && e.state !== 'offline')
        .map((e) => e.userId),
    );
  }

  /**
   * Restrict the CALL roles ('cam', 'mic') to these people; null publishes to
   * everyone, which is the default.
   *
   * The peer set is the ROOM — the mesh needs a connection to everybody for the
   * DataChannel fabric, and a lurker's connection is as real as a caller's. The
   * call is a subset of that, and publishing a camera to the whole room because
   * the connection happened to exist put twelve people's video on the wire for
   * an audience of four. The connection stays; the TRACK is what this gates.
   *
   * Screen share is deliberately unaffected: its audience is the room.
   */
  setPublishAudience(userIds: readonly UserId[] | null): void {
    if (this.closed) return;
    this.publishAudience = userIds === null ? null : new Set(userIds);
    for (const peer of this.peerMap.values()) {
      if (peer.lane !== null) continue;
      for (const role of AUDIENCE_ROLES) {
        const track = this.publishesTo(peer, role) ? (this.localTracks.get(role) ?? null) : null;
        try {
          this.applyTrackToPeer(peer, role, track);
        } catch (err) {
          this.onError(peer.userId, 'setPublishAudience', err);
        }
      }
    }
    // The camera ceiling is divided among the people who actually receive it.
    this.reconcileCapsEverywhere();
  }

  /**
   * Route a server-relayed webrtc.* event to the right negotiator, ADMITTING
   * the sender as a peer when we have not built one yet.
   *
   * Admission is what keeps the mesh convergent. Peers are otherwise derived
   * from presence, which each client receives on its own schedule, so there is
   * a window where A has B and B does not yet have A. Dropping B's view of A's
   * offer used to end the pair there and then: `negotiationneeded` does not
   * re-fire, so nothing ever re-offered and only a reload rebuilt both sides.
   *
   * Admitting is safe because the SERVER stamps `fromUserId` from the
   * authenticated socket (see the hub's webrtc.* handlers) — it is not a
   * client-supplied field. An inbound signal is therefore proof that an
   * authenticated member of THIS room is trying to reach us, which is exactly
   * the set presence would have listed a moment later.
   *
   * Churn is bounded from the other side: `syncPeers` stays authoritative, so
   * an admitted peer presence never confirms is removed by the next reconcile,
   * and a peer presence has just taken away is refused for ADMIT_SUPPRESS_MS
   * so its trailing signals cannot leave a phantom connection behind.
   *
   * Admission is also the ONLY way an auxiliary endpoint (a share running
   * beside somebody's call) ever gets a connection: nothing announces that a
   * person has a second mesh, so the second mesh offers and is recognised by
   * the id it offers under.
   *
   * A frame carrying a HELLO id is not a signal at all — it is the sender
   * telling us which of their endpoints they are. It is handled here because
   * the signalling channel is the only per-socket channel there is: presence
   * has one entry per person, so a token put there would name whichever of
   * their sockets wrote last.
   */
  handleSignal(ev: InboundSignal): void {
    if (this.closed) return;
    const fromUserId = ev.payload.fromUserId;
    if (fromUserId === this.localUserId) return;
    const hello = this.parseHello(ev.payload.connectionId);
    if (hello !== null) {
      this.noteAnnouncement(fromUserId, hello.token, hello.lane);
      return;
    }
    const roleHello = this.parseRoleHello(ev.payload.connectionId);
    if (roleHello !== null) {
      this.noteRoleAnnouncement(fromUserId, roleHello.streamId, roleHello.role);
      return;
    }
    // The connectionId is derived from (room, both ENDPOINTS): both sides
    // compute the same one, and — crucially — it does not change when either
    // side rebuilds its connection, so a rebuilt peer re-establishes against the
    // remote's existing one. Anything else is misrouted or forged, and drops.
    // The one case that is neither is a LIVE local peer holding some other id
    // (only reachable across incompatible builds): the canonical id supersedes
    // it, so the pair converges instead of being stranded on a dead incarnation.
    const endpoint = this.remoteEndpointFor(fromUserId, ev.payload.connectionId);
    if (endpoint === null) return;
    const canonical = this.connectionIdFor(endpoint);
    const key = peerKey(fromUserId, endpoint.name);
    let peer = this.peerMap.get(key);
    if (peer !== undefined && peer.connectionId !== canonical) {
      this.removePeer(key);
      peer = undefined;
    }
    if (peer === undefined) {
      if (this.admitSuppressed(fromUserId)) return;
      this.addPeer(fromUserId, endpoint);
      peer = this.peerMap.get(key);
      // addPeer failed and already reported through onError.
      if (peer === undefined) return;
    }
    // Being reached ON an endpoint id is the proof that the far side addresses
    // us per endpoint. Adopting it here — after the peer exists, so the person
    // never momentarily reads as gone — is what makes the switch symmetric: the
    // side that noticed the duplicate escalates, and the side that did not
    // follows on the first frame it receives.
    if (endpoint.announced && endpoint.lane === null) this.addressPerEndpoint(fromUserId);
    peer.negotiator.handleSignal(ev).catch((err: unknown) => {
      this.onError(fromUserId, 'signal', err);
    });
  }

  /** Publish/replace/remove a local media track for a role on every current and
   *  future peer connection. null removes.
   *
   *  Nothing of ours goes onto a link whose far end is an AUXILIARY endpoint:
   *  that endpoint is somebody's outbound-only share pipe (an offscreen
   *  document with no UI and no use for a camera), so sending to it would
   *  spend the local uplink twice over on media nobody renders. Nor does a call
   *  role go to somebody who is not on the call (see {@link
   *  setPublishAudience}). */
  setLocalTrack(role: TrackRole, track: MediaStreamTrackLike | null): void {
    if (track === null) {
      this.localTracks.delete(role);
    } else {
      this.localTracks.set(role, track);
    }
    for (const peer of this.peerMap.values()) {
      if (peer.lane !== null) continue;
      const forPeer = this.publishesTo(peer, role) ? track : null;
      try {
        this.applyTrackToPeer(peer, role, forPeer);
      } catch (err) {
        this.onError(peer.userId, 'setLocalTrack', err);
      }
    }
  }

  /** Snapshot of connection state PER PERSON: the best state across every
   *  endpoint they hold (see {@link STATE_RANK}). */
  connectionStates(): Map<UserId, MeshConnectionState> {
    const out = new Map<UserId, MeshConnectionState>();
    for (const peer of this.peerMap.values()) {
      const seen = out.get(peer.userId);
      if (seen === undefined || STATE_RANK[peer.state] > STATE_RANK[seen]) {
        out.set(peer.userId, peer.state);
      }
    }
    return out;
  }

  /** Currently connected (or connecting) remote peers, one entry per person
   *  however many endpoints they hold. */
  peers(): UserId[] {
    const out: UserId[] = [];
    const seen = new Set<UserId>();
    for (const peer of this.peerMap.values()) {
      if (seen.has(peer.userId)) continue;
      seen.add(peer.userId);
      out.push(peer.userId);
    }
    return out;
  }

  /** Poll per-link stats via statsPollFn (or pc.getStats). Peers whose poll
   *  rejects or lacks getStats are omitted. Each successful poll also
   *  classifies the link path (direct/relayed/unknown) from the selected
   *  candidate pair and drives the relay share cap.
   *
   *  Every endpoint is polled — classification drives the cap on each link
   *  independently — but the returned map is keyed by PERSON, so a person
   *  holding two endpoints is represented by their primary one. */
  async pollStats(): Promise<Map<UserId, unknown>> {
    const out = new Map<UserId, unknown>();
    await Promise.all(
      [...this.peerMap.entries()].map(async ([key, peer]) => {
        try {
          let stats: unknown;
          if (this.statsPollFn !== undefined) {
            stats = await this.statsPollFn(peer.pc);
          } else {
            if (peer.pc.getStats === undefined) return;
            stats = await peer.pc.getStats();
          }
          if (stats !== undefined && (peer.lane === null || !out.has(peer.userId))) {
            out.set(peer.userId, stats);
          }
          // The peer may have been removed while the poll was in flight.
          if (this.peerMap.get(key) !== peer) return;
          this.noteLinkClassification(peer, classifyLinkStats(stats));
        } catch (err) {
          this.onError(peer.userId, 'pollStats', err);
        }
      }),
    );
    return out;
  }

  /** Snapshot of link path states per PERSON (post-debounce). */
  linkStates(): Map<UserId, MeshLinkState> {
    const out = new Map<UserId, MeshLinkState>();
    for (const peer of this.peerMap.values()) {
      out.set(peer.userId, foldLink(out.get(peer.userId), peer.linkState));
    }
    return out;
  }

  /** Preflight for Mode B: the link path of a peer ALREADY connected (e.g.
   *  for voice), answered from the last completed stats poll — so whether a
   *  share would be relay-capped is known BEFORE the share track is added.
   *  'unknown' for unknown peers, and for links no poll has classified yet:
   *  a share to such a peer may run uncapped for up to one poll interval. */
  linkState(peerId: UserId): MeshLinkState {
    let seen: MeshLinkState | undefined;
    for (const peer of this.peerMap.values()) {
      if (peer.userId === peerId) seen = foldLink(seen, peer.linkState);
    }
    return seen ?? 'unknown';
  }

  /** Subscribe to per-peer link path CHANGES (debounced — one event per
   *  reported transition, never one per poll). Return unsubscribe. */
  onLinkState(fn: (peerId: UserId, state: MeshLinkState) => void): () => void {
    this.linkSubs.add(fn);
    return () => {
      this.linkSubs.delete(fn);
    };
  }

  /** Trigger an ICE restart on every connection to this person, and give each
   *  of them a fresh recovery budget: an explicit restart is a caller saying
   *  the link is worth another try, which is exactly what a spent budget
   *  means the mesh had stopped assuming. */
  restartIce(peerId: UserId): void {
    for (const [key, peer] of this.peerMap) {
      if (peer.userId !== peerId) continue;
      this.restartAndRenew(key, peer);
    }
  }

  /**
   * Re-read getIceServers() and repair every peer that was built before the
   * credentials arrived. A live RTCPeerConnection never re-reads its own
   * configuration, so without this a peer created during the fetch keeps its
   * fallback list forever.
   *
   * The mesh calls this itself on a short poll while such peers exist, so no
   * caller is REQUIRED to; a caller that owns the credential manager can call
   * it from onUpdate to repair on the same tick the credentials land.
   * Cheap and idempotent: with no provisional peers it does nothing, and peers
   * built WITH credentials are never touched (rotating TURN credentials must
   * not disturb a call that is already up).
   */
  refreshIceServers(): void {
    if (this.closed) return;
    const servers = this.getIceServers();
    if (servers.length === 0) return;
    for (const [key, peer] of [...this.peerMap]) {
      if (!peer.iceProvisional) continue;
      peer.iceProvisional = false;
      this.applyIceServers(key, peer, servers);
    }
  }

  /**
   * Subscribe to remote tracks. Return unsubscribe.
   *
   * `role` is what the SENDER published this track as, or null when this mesh
   * genuinely cannot tell — an un-announcing peer, an announcement that has not
   * landed, a stream id nobody claimed. Null is not a guess and must not be
   * treated as one: the caller's fallback for null is whatever it did before
   * roles existed, because the peers that answer null are the ones that predate
   * them (see {@link classifyLinkStats} for the same rule about link paths).
   */
  onRemoteTrack(
    fn: (
      peerId: UserId,
      track: MediaStreamTrackLike,
      streams: unknown[],
      role: TrackRole | null,
    ) => void,
  ): () => void {
    this.trackSubs.add(fn);
    return () => {
      this.trackSubs.delete(fn);
    };
  }

  /** Subscribe to per-peer connection state changes. Return unsubscribe. */
  onConnectionState(fn: (peerId: UserId, state: MeshConnectionState) => void): () => void {
    this.stateSubs.add(fn);
    return () => {
      this.stateSubs.delete(fn);
    };
  }

  /** Close every connection and the fabric. Idempotent. */
  close(): void {
    if (this.closed) return;
    this.closed = true;
    this.clearIceRepairTimer();
    for (const key of [...this.peerMap.keys()]) this.removePeer(key);
    this.fabric.close();
    this.trackSubs.clear();
    this.stateSubs.clear();
    this.linkSubs.clear();
    this.localTracks.clear();
    this.admitSuppressedUntil.clear();
    this.reportedStates.clear();
    this.reportedLinks.clear();
    this.dialed.clear();
    this.announced.clear();
    this.announcedTo.clear();
    this.perEndpoint.clear();
    this.announcedRoles.clear();
    this.roleAnnouncedTo.clear();
    this.roleStreams.clear();
  }

  // ---------- internals ----------

  /** Whether an inbound signal from this peer is still being ignored because
   *  presence removed them a moment ago. Expired entries are pruned here. */
  private admitSuppressed(peerId: UserId): boolean {
    const until = this.admitSuppressedUntil.get(peerId);
    if (until === undefined) return false;
    if (this.now() < until) return true;
    this.admitSuppressedUntil.delete(peerId);
    return false;
  }

  /** Poll getIceServers() while any peer is running on the fallback list. Stops
   *  as soon as the last one is repaired, or when the window closes and the
   *  fallback becomes the final answer (a credential fetch that never
   *  succeeds must leave a working STUN-only call, not a pending one). */
  private scheduleIceRepair(): void {
    if (this.closed) return;
    if (this.iceRepairTimer !== null) return;
    if (this.now() >= this.iceRepairDeadline) return;
    this.iceRepairTimer = this.setTimeoutFn(() => {
      this.iceRepairTimer = null;
      this.refreshIceServers();
      if (this.hasProvisionalPeers()) this.scheduleIceRepair();
    }, ICE_REPAIR_POLL_MS);
  }

  private clearIceRepairTimer(): void {
    if (this.iceRepairTimer === null) return;
    this.clearTimeoutFn(this.iceRepairTimer);
    this.iceRepairTimer = null;
  }

  private hasProvisionalPeers(): boolean {
    for (const peer of this.peerMap.values()) {
      if (peer.iceProvisional) return true;
    }
    return false;
  }

  /** Move one live peer onto a real ICE server list. setConfiguration keeps the
   *  connection, its senders and its channels alive, so it is applied to every
   *  provisional peer — a link that came up on STUN alone then has TURN to fall
   *  back on when it later fails. Only a link that has NOT come up gets the ICE
   *  restart that re-gathers candidates through the new servers. */
  private applyIceServers(key: string, peer: MeshPeer, servers: IceServerLike[]): void {
    const pc: RtcPeerConnectionLike & Reconfigurable = peer.pc;
    if (pc.setConfiguration !== undefined) {
      try {
        pc.setConfiguration({ iceServers: [...servers] });
        if (peer.state !== 'connected') this.restartAndRenew(key, peer);
        return;
      } catch (err) {
        this.onError(peer.userId, 'setConfiguration', err);
      }
    }
    // Without setConfiguration the only route onto the new list is a new
    // connection. Worth it for a peer still trying to reach us — that is the
    // one that needs TURN — and never worth dropping a call that already works.
    if (peer.state === 'connected') return;
    // The endpoint pair's connectionId does not change, so the remote answers
    // the fresh offer on the peer it already has; it does not rebuild too.
    this.removePeer(key);
    this.addPeer(peer.userId, { name: peer.name, lane: peer.lane, announced: peer.announced });
  }

  /**
   * Stable connection id for a pair of ENDPOINTS: identical on both sides,
   * because each side sorts the same two names.
   *
   * An ANNOUNCED endpoint is paired with our own token-bearing name, because
   * announcements are mutual — a peer we know the token of knows ours. Everyone
   * else is paired with the person-level name, which is byte-for-byte the id
   * this package has always produced: that is what lets a client that predates
   * endpoint tokens and one that has them still find each other.
   */
  private connectionIdFor(endpoint: RemoteEndpoint): string {
    const local = endpoint.announced ? this.localName : this.localBareName;
    const remote = endpoint.name;
    const [a, b] = local < remote ? [local, remote] : [remote, local];
    return `mesh:${this.roomId}:${a}~${b}`;
  }

  /** The person-level endpoint of an identity — what a peer that announced
   *  nothing is dialled as, and what an old build always derives. */
  private personEndpoint(userId: UserId): RemoteEndpoint {
    return { name: endpointName(userId, null, null), lane: null, announced: false };
  }

  /** Every endpoint of an identity we currently know how to address, in the
   *  order they announced. Empty when we run person-level, or when the far side
   *  has announced nothing. */
  private announcedEndpoints(userId: UserId): RemoteEndpoint[] {
    // Announcements are only usable BOTH ways: a mesh with no token of its own
    // cannot be addressed per endpoint, so it must keep addressing others by
    // person or the two sides would derive different ids.
    if (this.endpointId === null) return [];
    const out: RemoteEndpoint[] = [];
    for (const [token, lane] of this.announced.get(userId) ?? []) {
      out.push({ name: endpointName(userId, lane, token), lane, announced: true });
    }
    return out;
  }

  /**
   * Which of the sender's endpoints an inbound signal belongs to, or null when
   * the id is not one this pair could have derived (misrouted, forged, or —
   * the common case now — addressed to the OTHER mesh of an identity whose
   * signals the hub fans out to all of their sockets).
   *
   * Candidates are ENUMERATED and compared whole, never parsed back out of the
   * id: a UserId is only constrained to be a non-empty string, so no separator
   * can be relied on to split one.
   */
  private remoteEndpointFor(fromUserId: UserId, connectionId: string): RemoteEndpoint | null {
    for (const endpoint of this.announcedEndpoints(fromUserId)) {
      // An auxiliary mesh answers primaries and nobody else (see below).
      if (this.lane !== null && endpoint.lane !== null) continue;
      if (connectionId === this.connectionIdFor(endpoint)) return endpoint;
    }
    // The person-level id is refused once this identity is addressed per
    // endpoint: it is the id BOTH of their devices would derive, and accepting
    // it is exactly how a second tab used to take over the first one's link.
    if (!this.perEndpoint.has(fromUserId)) {
      const person = this.personEndpoint(fromUserId);
      if (connectionId === this.connectionIdFor(person)) return person;
    }
    // An auxiliary mesh answers primaries and nobody else. Two auxiliaries are
    // both outbound-only media pipes with nothing to say to each other, and
    // refusing them here is what keeps the "always offers first" rule — and so
    // the no-round-trip derivation — sound in both directions.
    if (this.lane !== null) return null;
    // A lane stays addressable by the person-level scheme however this identity
    // is otherwise addressed: an auxiliary endpoint never announces (it is
    // never dialled), and its id cannot collide with a primary's anyway.
    for (const lane of MESH_LANES) {
      const aux: RemoteEndpoint = {
        name: endpointName(fromUserId, lane, null),
        lane,
        announced: false,
      };
      if (connectionId === this.connectionIdFor(aux)) return aux;
    }
    return null;
  }

  /* ---------- endpoint announcements ---------- */

  /** The connectionId this mesh announces itself under. It is not a pair id and
   *  cannot be mistaken for one: nothing derives an id with `hello` where the
   *  first endpoint name goes, and a build that has never heard of
   *  announcements drops it as unroutable, which is exactly right. */
  private helloId(): string {
    return `mesh:${this.roomId}:hello:${this.lane ?? ''}:${this.endpointId ?? ''}`;
  }

  /** Read an inbound connectionId as an announcement, or null when it is an
   *  ordinary pair id. The prefix is OUR OWN room's, so everything before the
   *  remainder is a fixed known string; the remainder is split once, and both
   *  halves are validated against fixed vocabularies before use. */
  private parseHello(connectionId: string): { lane: MeshLane | null; token: string } | null {
    const prefix = `mesh:${this.roomId}:hello:`;
    if (!connectionId.startsWith(prefix)) return null;
    const rest = connectionId.slice(prefix.length);
    const split = rest.indexOf(':');
    if (split < 0) return null;
    const laneName = rest.slice(0, split);
    const token = rest.slice(split + 1);
    if (!ENDPOINT_TOKEN_RE.test(token)) return null;
    if (laneName === '') return { lane: null, token };
    const lane = MESH_LANES.find((l) => l === laneName);
    if (lane === undefined) return null;
    return { lane, token };
  }

  /** Tell one identity which endpoint we are. Idempotent per person: they only
   *  need it once, and the reply path below re-sends it when it turns out they
   *  did not have it. Silent for a mesh with no token — it has nothing to say,
   *  and every peer already knows how to address it. */
  private announceTo(userId: UserId): void {
    if (this.endpointId === null) return;
    if (this.announcedTo.has(userId)) return;
    this.announcedTo.add(userId);
    this.sendHello(userId);
  }

  private sendHello(userId: UserId): void {
    this.send({
      type: 'webrtc.offer',
      roomId: this.roomId,
      seq: 0,
      ts: Math.floor(this.now()),
      payload: { targetUserId: userId, connectionId: this.helloId(), sdp: '' },
    });
  }

  /**
   * Record one endpoint of a remote identity, and answer in kind when it is
   * news to us.
   *
   * Answering only NEW announcements is what terminates the exchange: our reply
   * is old news to a peer that already had us, so it does not reply back. The
   * reply exists because presence reaches the two sides at different times —
   * whoever heard of the other first would otherwise never be announced to.
   */
  private noteAnnouncement(userId: UserId, token: string, lane: MeshLane | null): void {
    if (this.endpointId === null) return;
    let byToken = this.announced.get(userId);
    if (byToken === undefined) {
      byToken = new Map();
      this.announced.set(userId, byToken);
    }
    if (byToken.has(token)) return;
    if (byToken.size >= MAX_ENDPOINTS_PER_USER && !this.evictEndpoint(userId, byToken)) {
      // Every slot is spent on a live connection. Refusing is the honest end:
      // the alternative is dropping a link that works for one that might.
      return;
    }
    byToken.set(token, lane);
    // Two primary endpoints of one identity is the collision this exists to
    // stop, and the side that can SEE it is the side holding both. It escalates;
    // the other follows on the first frame that arrives on an endpoint id.
    if (this.primaryEndpointCount(userId) >= 2) this.addressPerEndpoint(userId);
    else this.reconcileEndpoints(userId);
    this.sendHello(userId);
    this.announcedTo.add(userId);
  }

  /** How many of an identity's announced endpoints are dialable primaries. */
  private primaryEndpointCount(userId: UserId): number {
    let count = 0;
    for (const lane of (this.announced.get(userId) ?? new Map<string, MeshLane | null>()).values()) {
      if (lane === null) count += 1;
    }
    return count;
  }

  /** Free one announcement slot, preferring tokens with no live connection
   *  behind them — a reloaded tab leaves its old token behind, and the
   *  budget has to be reclaimable or the fifth reload never connects. */
  private evictEndpoint(userId: UserId, byToken: Map<string, MeshLane | null>): boolean {
    for (const [token, lane] of byToken) {
      const key = peerKey(userId, endpointName(userId, lane, token));
      const peer = this.peerMap.get(key);
      if (peer !== undefined && peer.state === 'connected') continue;
      byToken.delete(token);
      if (peer !== undefined) this.removePeer(key);
      return true;
    }
    return false;
  }

  /** Address this identity by ENDPOINT from here on. One-way while they are in
   *  the room: falling back to the person-level id is what let their second
   *  device reset the first one's ICE and DTLS, over and over. */
  private addressPerEndpoint(userId: UserId): void {
    if (this.endpointId === null) return;
    if (!this.perEndpoint.has(userId)) this.perEndpoint.add(userId);
    this.reconcileEndpoints(userId);
    // A peer that is not dialled is not reconciled above, so its superseded
    // person-level link is retired here.
    const personKey = peerKey(userId, endpointName(userId, null, null));
    if (this.peerMap.has(personKey)) this.removePeer(personKey);
  }

  /* ---------- track role announcements ---------- */

  /**
   * The connectionId a role announcement rides under.
   *
   * Same carrier as the endpoint hello above, for the same reason: the
   * signalling channel is the only PER-SOCKET channel there is. Nothing
   * derives a pair id with `role` where the first endpoint name goes, so a
   * build that has never heard of role announcements drops this as unroutable
   * — which is exactly right, and is what leaves it answering null.
   */
  private roleHelloId(role: TrackRole, streamId: string): string {
    return `mesh:${this.roomId}:role:${role}:${streamId}`;
  }

  /** Read an inbound connectionId as a role announcement, or null when it is
   *  something else. Both halves are validated against fixed rules before
   *  either is stored, and the stream id is only ever compared afterwards. */
  private parseRoleHello(connectionId: string): { role: TrackRole; streamId: string } | null {
    const prefix = `mesh:${this.roomId}:role:`;
    if (!connectionId.startsWith(prefix)) return null;
    const rest = connectionId.slice(prefix.length);
    const split = rest.indexOf(':');
    if (split < 0) return null;
    const roleName = rest.slice(0, split);
    const streamId = rest.slice(split + 1);
    if (!STREAM_ID_RE.test(streamId)) return null;
    const role = TRACK_ROLES.find((r) => r === roleName);
    if (role === undefined) return null;
    return { role, streamId };
  }

  /**
   * The stream a role's tracks ride on, minted on first use.
   *
   * One stream per ROLE, not per peer: the same local track is published to
   * every connection, and what the far side is being told is what the track
   * IS. Null means this mesh publishes that role bare — no factory was
   * injected, the factory threw, or it returned an id no announcement could
   * carry — and every receiver then answers null for it.
   */
  private roleStream(role: TrackRole): MediaStreamLike | null {
    const held = this.roleStreams.get(role);
    if (held !== undefined) return held;
    if (this.mediaStreamFactory === undefined) {
      this.roleStreams.set(role, null);
      return null;
    }
    let stream: MediaStreamLike | null = null;
    try {
      const minted = this.mediaStreamFactory();
      // Two roles sharing one id would announce each other away, and the far
      // side would name tracks by whichever announcement landed last. A factory
      // that repeats itself gets one role named and the rest published bare —
      // null answers, never wrong ones.
      if (STREAM_ID_RE.test(minted.id) && !this.roleStreamIdTaken(minted.id)) stream = minted;
    } catch (err) {
      // Ours, not a peer's — but a throwing platform primitive still has to
      // surface here rather than escape an event path.
      this.onError(this.localUserId, 'mediaStreamFactory', err);
    }
    this.roleStreams.set(role, stream);
    return stream;
  }

  /** Whether another role already publishes under this stream id. */
  private roleStreamIdTaken(streamId: string): boolean {
    for (const stream of this.roleStreams.values()) {
      if (stream !== null && stream.id === streamId) return true;
    }
    return false;
  }

  /** Everyone owed an announcement: the people we dial, plus anyone whose
   *  connection we hold without dialling (an admitted auxiliary endpoint). */
  private announcementAudience(): Set<UserId> {
    const out = new Set<UserId>(this.dialed);
    for (const peer of this.peerMap.values()) out.add(peer.userId);
    return out;
  }

  /** Tell one identity which stream ids carry which of our roles — only the
   *  ones they have not been told. Silent for a mesh that publishes bare: it
   *  has nothing to say, and its receivers correctly answer null. */
  private announceRolesTo(userId: UserId): void {
    if (this.mediaStreamFactory === undefined) return;
    let told = this.roleAnnouncedTo.get(userId);
    if (told === undefined) {
      told = new Set();
      this.roleAnnouncedTo.set(userId, told);
    }
    for (const [role, stream] of this.roleStreams) {
      if (stream === null || told.has(role)) continue;
      told.add(role);
      this.send({
        type: 'webrtc.offer',
        roomId: this.roomId,
        seq: 0,
        ts: Math.floor(this.now()),
        payload: {
          targetUserId: userId,
          connectionId: this.roleHelloId(role, stream.id),
          sdp: '',
        },
      });
    }
  }

  /**
   * Put a local track on one link, under the stream that names its role.
   *
   * The ORDER here is the entire guarantee. `send` is synchronous; the offer
   * that will carry this track is not — it waits on createOffer /
   * setLocalDescription — so an announcement written first is always ahead of
   * that offer on the same ordered socket, and the far side holds the mapping
   * before its `ontrack` fires. Reverse the two and the receiver is back to
   * answering null for a track it could have named.
   */
  private publishOn(
    peer: MeshPeer,
    role: TrackRole,
    track: MediaStreamTrackLike,
  ): RtpSenderLike {
    const stream = this.roleStream(role);
    if (stream === null) return peer.pc.addTrack(track);
    // ANNOUNCE FIRST, and the ordering is the whole guarantee. `send` is
    // synchronous while `createOffer`/`setLocalDescription` are not, so an
    // announcement written here is already on the same ordered socket ahead of
    // the offer that carries this track — which is what makes the receiver
    // certain to hold the id→role mapping by the time `ontrack` fires for it.
    // Announcing after `addTrack` still lands eventually, but it races its own
    // offer, and the track it loses to is the one this exists to name.
    for (const userId of this.announcementAudience()) this.announceRolesTo(userId);
    return peer.pc.addTrack(track, stream);
  }

  /** Record one stream-id→role fact about a remote identity. */
  private noteRoleAnnouncement(userId: UserId, streamId: string, role: TrackRole): void {
    let byStream = this.announcedRoles.get(userId);
    if (byStream === undefined) {
      byStream = new Map();
      this.announcedRoles.set(userId, byStream);
    }
    if (byStream.get(streamId) === role) return;
    byStream.delete(streamId);
    // Oldest out first: unlike an endpoint token there is no live connection
    // behind a stream id to protect, and a mapping a peer floods out of its own
    // budget costs that peer a null answer on its own tracks — never a wrong
    // role on anyone else's.
    while (byStream.size >= MAX_ROLE_STREAMS_PER_USER) {
      const oldest = byStream.keys().next();
      if (oldest.done === true) break;
      byStream.delete(oldest.value);
    }
    byStream.set(streamId, role);
  }

  /**
   * What role a remote track was published as, or null when this mesh cannot
   * say — an un-announcing peer, a stream nobody claimed, an announcement that
   * never arrived. Null is the honest answer and never a guess; the two things
   * this WILL answer from are both declarations the far side made.
   */
  private roleOfRemoteTrack(
    peer: MeshPeer,
    track: MediaStreamTrackLike,
    streams: unknown[],
  ): TrackRole | null {
    const byStream = this.announcedRoles.get(peer.userId);
    if (byStream !== undefined) {
      for (const stream of streams) {
        const id = streamIdOf(stream);
        if (id === null) continue;
        const role = byStream.get(id);
        if (role !== undefined) return role;
      }
    }
    // A LANE declares what a whole mesh is FOR. It is carried in the
    // connectionId and matched against MESH_LANES before the link is built, and
    // the 'share' lane is somebody's outbound-only share pipe: it is refused
    // our own media (see publishesTo) and holds no camera to offer. Reading the
    // link's declared purpose is not guessing from the track — and it is what
    // names an extension share, which announces nothing.
    if (peer.lane === 'share') return track.kind === 'video' ? 'share' : 'share-audio';
    return null;
  }

  /** Bring the connections we hold to one identity in line with how we address
   *  them: one per announced endpoint, or one person-level connection. Adds
   *  before it removes, so a person never momentarily reads as gone. */
  private reconcileEndpoints(userId: UserId): void {
    if (this.closed) return;
    if (!this.dialed.has(userId)) return;
    const desired = this.perEndpoint.has(userId)
      ? this.announcedEndpoints(userId).filter((e) => e.lane === null)
      : [this.personEndpoint(userId)];
    for (const endpoint of desired) {
      if (!this.peerMap.has(peerKey(userId, endpoint.name))) this.addPeer(userId, endpoint);
    }
    const keep = new Set(desired.map((e) => e.name));
    for (const [key, peer] of [...this.peerMap]) {
      // Auxiliary links are admitted, never dialled: they are not ours to
      // reconcile, and a share must survive its owner's tabs coming and going.
      if (peer.userId !== userId || peer.lane !== null) continue;
      if (keep.has(peer.name)) continue;
      this.removePeer(key);
    }
  }

  private addPeer(peerId: UserId, endpoint: RemoteEndpoint): void {
    const { name, lane } = endpoint;
    const key = peerKey(peerId, name);
    // Only a link between two PRIMARY meshes carries the fabric: an auxiliary
    // link attaching 'sync' under the same user id would replace the call's
    // channels with a share's and take sync and file transfer down with it. An
    // auxiliary link carries media and nothing else.
    const fabricLink = this.lane === null && lane === null;
    // The fabric is keyed by USER, and a person can now be here from two
    // devices. Both build the channels — they cost one SCTP stream and are what
    // makes `negotiationneeded` fire on a link with no media — but only one is
    // ATTACHED, or the second would close the first's channels out from under
    // the beacon and file layers. The rest stand by (see `promoteFabric`).
    const ownsFabric = fabricLink && this.fabricOwnerOf(peerId) === undefined;
    try {
      // An empty list here does NOT mean "no ice servers wanted": callers start
      // the TURN credential fetch without awaiting it, so every peer built in
      // that window would otherwise run host-candidate-only for its whole life.
      const configured = this.getIceServers();
      const iceProvisional = this.iceServersProvided && configured.length === 0;
      const iceServers = configured.length === 0 ? [...this.fallbackIceServers] : configured;
      const pc = this.rtcFactory({ iceServers });
      const connectionId = this.connectionIdFor(endpoint);

      // Pre-negotiated fabric channels: both sides create the same fixed ids,
      // so no in-band datachannel negotiation is needed.
      const channels = new Map<ChannelLabel, DataChannelLike>();
      if (fabricLink) {
        for (const label of FABRIC_LABELS) {
          const dc = pc.createDataChannel(label, {
            negotiated: true,
            id: CHANNEL_IDS[label],
            ordered: true,
          });
          channels.set(label, dc);
          if (ownsFabric) this.fabric.attach(peerId, label, dc);
        }
      }

      const negotiator = new PerfectNegotiator({
        pc,
        roomId: this.roomId,
        localUserId: this.localUserId,
        remoteUserId: peerId,
        connectionId,
        send: this.send,
        now: this.now,
        setTimeoutFn: this.setTimeoutFn,
        clearTimeoutFn: this.clearTimeoutFn,
        ...(this.offerRetryMs === undefined ? {} : { offerRetryMs: this.offerRetryMs }),
        onError: (context, err) => {
          this.onError(peerId, context, err);
        },
      });

      const peer: MeshPeer = {
        pc,
        negotiator,
        senders: new Map(),
        state: pc.connectionState,
        connectionId,
        userId: peerId,
        name,
        lane,
        announced: endpoint.announced,
        channels,
        fabricOwner: ownsFabric,
        linkState: 'unknown',
        unknownStreak: 0,
        caps: new Map(),
        recoveryTimer: null,
        iceRestarts: 0,
        recoveryExhausted: false,
        iceProvisional,
      };
      this.peerMap.set(key, peer);

      pc.ontrack = (ev) => {
        const role = this.roleOfRemoteTrack(peer, ev.track, ev.streams);
        for (const fn of [...this.trackSubs]) fn(peerId, ev.track, ev.streams, role);
      };
      pc.onconnectionstatechange = () => {
        peer.state = pc.connectionState;
        this.reportState(peerId);
        this.onPeerState(key, peer);
      };
      if (fabricLink) {
        // Defensive: a non-negotiated inbound channel with a known label joins
        // the fabric like any other — but only from the link that owns it.
        pc.ondatachannel = (ev) => {
          const label = ev.channel.label;
          if (label !== 'sync' && label !== 'file') return;
          peer.channels.set(label, ev.channel);
          if (peer.fabricOwner) this.fabric.attach(peerId, label, ev.channel);
        };
      }

      // Tracks published before this peer existed join its connection now —
      // unless the far end is an auxiliary endpoint, which publishes to us and
      // renders nothing of ours, or is not on the call (see setLocalTrack).
      if (lane === null) {
        for (const [role, track] of this.localTracks) {
          if (!this.publishesTo(peer, role)) continue;
          peer.senders.set(role, this.publishOn(peer, role, track));
        }
        this.reconcileCapsEverywhere();
      }

      if (iceProvisional) {
        this.iceRepairDeadline = this.now() + ICE_REPAIR_WINDOW_MS;
        this.scheduleIceRepair();
      }
    } catch (err) {
      // A partially constructed peer (e.g. createDataChannel threw after the
      // first channel attached) must not leave fabric zombies behind.
      if (ownsFabric) this.fabric.detachPeer(peerId);
      this.onError(peerId, 'addPeer', err);
    }
  }

  private removePeer(key: string): void {
    const peer = this.peerMap.get(key);
    if (peer === undefined) return;
    this.peerMap.delete(key);
    this.clearRecovery(peer);
    try {
      peer.negotiator.dispose();
      peer.pc.ontrack = null;
      peer.pc.onconnectionstatechange = null;
      peer.pc.ondatachannel = null;
      peer.pc.close();
    } catch (err) {
      this.onError(peer.userId, 'removePeer', err);
    }
    // One fewer receiver is a bigger slice of the camera ceiling for everyone
    // left: a cap that only ever tightened would hold the last two people in
    // the room at the bitrate a full one needed.
    if (!this.closed) this.reconcileCapsEverywhere();
    if (peer.fabricOwner) {
      this.fabric.detachPeer(peer.userId);
      // Another device of theirs may still be reachable; the fabric follows it
      // rather than staying down until they reload.
      this.promoteFabric(peer.userId);
    }
    // 'closed' means the PERSON has nothing left — callers drop their retained
    // tracks on it. A share ending while its owner is still on the call must
    // therefore not announce it; the call's own state is re-announced instead.
    if (this.hasEndpoints(peer.userId)) {
      this.reportState(peer.userId);
      this.reportLink(peer.userId);
      return;
    }
    this.reportedStates.delete(peer.userId);
    this.reportedLinks.delete(peer.userId);
    for (const fn of [...this.stateSubs]) fn(peer.userId, 'closed');
  }

  private hasEndpoints(userId: UserId): boolean {
    for (const peer of this.peerMap.values()) {
      if (peer.userId === userId) return true;
    }
    return false;
  }

  /** The best state across a person's endpoints — see {@link STATE_RANK} —
   *  or undefined when they hold none. */
  private stateOf(userId: UserId): MeshConnectionState | undefined {
    let best: MeshConnectionState | undefined;
    for (const peer of this.peerMap.values()) {
      if (peer.userId !== userId) continue;
      if (best === undefined || STATE_RANK[peer.state] > STATE_RANK[best]) best = peer.state;
    }
    return best;
  }

  /** Announce a person's connection state, when the fold over their endpoints
   *  has actually moved. Someone with two endpoints must produce one stream of
   *  events, not two interleaved ones a subscriber would see flap. */
  private reportState(userId: UserId): void {
    const state = this.stateOf(userId);
    if (state === undefined) return;
    if (this.reportedStates.get(userId) === state) return;
    this.reportedStates.set(userId, state);
    for (const fn of [...this.stateSubs]) fn(userId, state);
  }

  /** Announce a person's link path, when the fold over their endpoints has
   *  actually moved. */
  private reportLink(userId: UserId): void {
    if (!this.hasEndpoints(userId)) return;
    const state = this.linkState(userId);
    if (this.reportedLinks.get(userId) === state) return;
    this.reportedLinks.set(userId, state);
    for (const fn of [...this.linkSubs]) fn(userId, state);
  }

  /** Whether a role's track belongs on this link at all: never on an auxiliary
   *  endpoint, and — for the call roles — never on somebody the audience
   *  leaves out. */
  private publishesTo(peer: MeshPeer, role: TrackRole): boolean {
    if (peer.lane !== null) return false;
    if (this.publishAudience === null) return true;
    if (!AUDIENCE_ROLES.includes(role)) return true;
    return this.publishAudience.has(peer.userId);
  }

  /** How many links a camera is currently published on. The ceiling is divided
   *  among them, because a mesh encodes and uploads one copy per link. */
  private camReceiverCount(): number {
    let count = 0;
    for (const peer of this.peerMap.values()) {
      if (this.publishesTo(peer, 'cam')) count += 1;
    }
    return Math.max(1, count);
  }

  private applyTrackToPeer(
    peer: MeshPeer,
    role: TrackRole,
    track: MediaStreamTrackLike | null,
  ): void {
    const sender = peer.senders.get(role);
    if (track === null) {
      if (sender === undefined) return;
      // Mute, do not demolish. `removeTrack` retires the transceiver and forces
      // a full renegotiation, and on a sendrecv m-line that disturbs the
      // RECEIVE direction too — turning your own camera off could stop the
      // remote camera arriving on that line. Turning it back on then added a
      // second renegotiation immediately behind the first, and whichever one
      // glare handling discarded, the camera did not come back until you
      // toggled again. `replaceTrack(null)` keeps the sender and the
      // transceiver, needs NO renegotiation at all, and re-arms instantly when
      // a track returns through the replaceTrack branch below.
      if (sender.replaceTrack !== undefined) {
        sender.replaceTrack(null).catch((err: unknown) => {
          this.onError(peer.userId, 'replaceTrack', err);
        });
        peer.caps.delete(role);
        return;
      }
      // No replaceTrack on this platform: the old teardown is the only option.
      peer.pc.removeTrack(sender);
      peer.senders.delete(role);
      peer.caps.delete(role);
      return;
    }
    if (sender === undefined) {
      peer.senders.set(role, this.publishOn(peer, role, track));
      // Preflight payoff: on a link already classified relayed, the brand-new
      // share sender is capped before its first frame, not at the next poll.
      peer.caps.delete(role);
      this.reconcileCaps(peer);
      return;
    }
    if (sender.replaceTrack !== undefined) {
      // Same sender, same parameters: an existing cap survives the swap.
      sender.replaceTrack(track).catch((err: unknown) => {
        // A failed swap leaves the old track publishing, which is strictly
        // safer than dropping the role.
        this.onError(peer.userId, 'replaceTrack', err);
      });
      return;
    }
    peer.pc.removeTrack(sender);
    peer.senders.set(role, this.publishOn(peer, role, track));
    peer.caps.delete(role);
    this.reconcileCaps(peer);
  }

  /** Fold one poll's classification into the reported link state. Same-state
   *  polls are silent; a KNOWN state demotes to 'unknown' only after
   *  UNKNOWN_POLLS_TO_DEMOTE consecutive unknown reads (ICE-restart flap
   *  damping), while direct<->relayed transitions report immediately. */
  private noteLinkClassification(peer: MeshPeer, next: MeshLinkState): void {
    if (next === peer.linkState) {
      peer.unknownStreak = 0;
      return;
    }
    if (next === 'unknown') {
      peer.unknownStreak += 1;
      if (peer.unknownStreak < UNKNOWN_POLLS_TO_DEMOTE) return;
    }
    peer.unknownStreak = 0;
    peer.linkState = next;
    this.reportLink(peer.userId);
    this.reconcileCaps(peer);
  }

  /**
   * The ceiling a role should carry on this link right now: a bitrate in bps,
   * null for "no ceiling", or 'hold' for "an uncertain link keeps whatever it
   * has".
   *
   * 'share' answers to the link PATH — it is a TURN bill, and a direct link
   * costs nothing to run at full quality. 'cam' answers to the ROOM: every
   * receiver is another encode off the same uplink, so its ceiling shrinks as
   * people join whether the path is relayed or not. Audio is never capped —
   * not the microphone, and not the share's own soundtrack, which is the half
   * of a share people notice going missing.
   */
  private capFor(peer: MeshPeer, role: TrackRole): number | null | 'hold' {
    if (role === 'share') {
      if (this.capRelayedVideoKbps === undefined) return null;
      if (peer.linkState === 'relayed') return this.capRelayedVideoKbps * 1000;
      if (peer.linkState === 'direct') return null;
      return 'hold';
    }
    if (role === 'cam') {
      if (this.capCamKbps === undefined) return null;
      const perLink = Math.floor(this.capCamKbps / this.camReceiverCount());
      return Math.max(MIN_CAM_KBPS, perLink) * 1000;
    }
    return null;
  }

  /** Bring every video sender on one link in line with {@link capFor}.
   *  setParameters is async and may reject; a rejection surfaces via onError
   *  and never interrupts the call. */
  private reconcileCaps(peer: MeshPeer): void {
    for (const role of ['share', 'cam'] as const) {
      const sender = peer.senders.get(role);
      if (sender === undefined) continue;
      const want = this.capFor(peer, role);
      if (want === 'hold') continue;
      const applied = peer.caps.get(role);
      if (want === applied) continue;
      const context = role === 'share' ? 'shareCap' : 'camCap';
      if (want === null) {
        if (applied === undefined) continue;
        peer.caps.delete(role);
        clearMaxBitrate(sender, applied).catch((err: unknown) => {
          this.onError(peer.userId, context, err);
        });
        continue;
      }
      peer.caps.set(role, want);
      applyMaxBitrate(sender, want).catch((err: unknown) => {
        this.onError(peer.userId, context, err);
      });
    }
  }

  /** Re-derive every link's ceilings. The camera's depends on how many links
   *  there are, so adding or removing one moves it on all the others. */
  private reconcileCapsEverywhere(): void {
    for (const peer of this.peerMap.values()) this.reconcileCaps(peer);
  }

  /* ---------- link recovery ---------- */

  /** The endpoint currently carrying the fabric for this person, if any. */
  private fabricOwnerOf(userId: UserId): MeshPeer | undefined {
    for (const peer of this.peerMap.values()) {
      if (peer.userId === userId && peer.fabricOwner) return peer;
    }
    return undefined;
  }

  /** Hand the fabric to another endpoint of this person after the owner went
   *  away. The channels were created with the link and have been open all
   *  along; only the attachment moves. */
  private promoteFabric(userId: UserId): void {
    if (this.lane !== null) return;
    if (this.fabricOwnerOf(userId) !== undefined) return;
    for (const peer of this.peerMap.values()) {
      if (peer.userId !== userId || peer.lane !== null || peer.channels.size === 0) continue;
      peer.fabricOwner = true;
      for (const [label, dc] of peer.channels) this.fabric.attach(userId, label, dc);
      return;
    }
  }

  /**
   * React to one link's connection state.
   *
   * 'failed' and 'disconnected' both mean media has stopped; they differ in how
   * likely it is to come back on its own, which is what the grace window
   * encodes. Recovery is BOUNDED either way: an ICE restart against a path that
   * is genuinely gone accomplishes nothing, and repeating it forever leaves the
   * UI saying "trying to get it back" at a link that is never coming back.
   */
  private onPeerState(key: string, peer: MeshPeer): void {
    if (peer.state === 'connected') {
      // Whatever it took, it worked: the next outage starts from a full budget.
      this.clearRecovery(peer);
      peer.iceRestarts = 0;
      peer.recoveryExhausted = false;
      return;
    }
    if (peer.state === 'failed') {
      this.scheduleRecovery(key, peer, ICE_RESTART_BACKOFF_MS[0] ?? 0);
      return;
    }
    if (peer.state === 'disconnected') {
      // ICE says 'disconnected' for a wifi roam or a few lost consent checks,
      // and most of those heal untouched. Give it the grace window before
      // treating it as an outage — and, crucially, do not leave it there.
      this.scheduleRecovery(key, peer, DISCONNECT_GRACE_MS);
    }
  }

  /**
   * Spend one ICE restart from OUTSIDE the recovery loop and put the link back
   * on a full budget.
   *
   * Two things genuinely change a dead link's odds: a caller asking for another
   * try, and real TURN credentials landing on a peer that was built without
   * any. Both deserve a budget the loop had written off — but the try still has
   * to be FOLLOWED UP, or an explicit restart on a wedged link is the last
   * thing that ever happens to it, which is the wedge this loop exists to
   * prevent, one attempt further along.
   */
  private restartAndRenew(key: string, peer: MeshPeer): void {
    this.clearRecovery(peer);
    peer.recoveryExhausted = false;
    peer.negotiator.restartIce();
    if (peer.state !== 'failed' && peer.state !== 'disconnected') {
      // Not in an outage — a peer that has never come up yet. Nothing to
      // follow up on: onPeerState arms the loop if this restart does not take.
      peer.iceRestarts = 0;
      return;
    }
    // The restart just spent is the first of the new budget, not a freebie.
    peer.iceRestarts = 1;
    this.scheduleRecovery(key, peer, ICE_RESTART_BACKOFF_MS[1] ?? 0);
  }

  /** Whether this person is reachable RIGHT NOW on one of their other
   *  endpoints. Deliberately strict — only a connected sibling counts, so a
   *  person whose devices are all struggling gets the honest failure rather
   *  than having every link quietly dropped on the strength of another one
   *  that is not working either. */
  private connectedElsewhere(peer: MeshPeer): boolean {
    for (const other of this.peerMap.values()) {
      if (other === peer || other.userId !== peer.userId) continue;
      if (other.state === 'connected') return true;
    }
    return false;
  }

  /** Drop an announced endpoint's token, so its slot in the per-user budget
   *  comes back and no reconcile rebuilds the link we just gave up on. */
  private forgetEndpoint(peer: MeshPeer): void {
    const byToken = this.announced.get(peer.userId);
    if (byToken === undefined) return;
    for (const [token, lane] of byToken) {
      if (endpointName(peer.userId, lane, token) !== peer.name) continue;
      byToken.delete(token);
      return;
    }
  }

  private scheduleRecovery(key: string, peer: MeshPeer, delayMs: number): void {
    if (this.closed) return;
    if (peer.recoveryTimer !== null) return;
    if (peer.recoveryExhausted) return;
    peer.recoveryTimer = this.setTimeoutFn(() => {
      peer.recoveryTimer = null;
      this.runRecovery(key, peer);
    }, delayMs);
  }

  private clearRecovery(peer: MeshPeer): void {
    if (peer.recoveryTimer === null) return;
    this.clearTimeoutFn(peer.recoveryTimer);
    peer.recoveryTimer = null;
  }

  private runRecovery(key: string, peer: MeshPeer): void {
    if (this.closed) return;
    if (this.peerMap.get(key) !== peer) return;
    if (peer.state !== 'failed' && peer.state !== 'disconnected') return;
    if (peer.lane !== null) {
      // An AUXILIARY endpoint is not ours to repair. Presence still lists the
      // person — their call is right there — so no reconcile will ever clean
      // this up, and restarting ICE at an offscreen document that closed when
      // the share ended retries forever at nothing. Drop it: a share that comes
      // back offers again and is admitted again.
      this.removePeer(key);
      return;
    }
    if (peer.iceRestarts >= ICE_RESTART_LIMIT) {
      // A dead ENDPOINT of somebody we are still connected to elsewhere is a
      // closed tab, not a lost call. Nothing else would ever clean it up —
      // presence still lists the person, and their token stays announced — so
      // it is dropped here, token and all, and the room is told nothing. They
      // never went anywhere.
      if (peer.announced && this.connectedElsewhere(peer)) {
        this.forgetEndpoint(peer);
        this.removePeer(key);
        return;
      }
      peer.recoveryExhausted = true;
      // Say so once. The app layer's honest answer to this is a sentence, not
      // another spinner: nothing else here is going to bring the link back.
      this.onError(peer.userId, 'iceRecoveryExhausted', new Error('link did not recover'));
      return;
    }
    peer.iceRestarts += 1;
    peer.negotiator.restartIce();
    const next = ICE_RESTART_BACKOFF_MS[peer.iceRestarts] ?? ICE_RESTART_BACKOFF_MS.at(-1) ?? 0;
    this.scheduleRecovery(key, peer, next);
  }
}
