import type { Metadata } from 'next';
import type { InviteCode } from '@gather/contracts';
import { JoinClient } from './join-client';

/** The invite link is the most-shared URL in the product, so its card is the
 *  first thing many people ever see of Gather. The code itself is deliberately
 *  NOT in the title or the description: link previews are generated by whatever
 *  chat app the invite was pasted into, and an invite code is a credential. */
export const metadata: Metadata = {
  title: 'You’re invited',
  description: 'Someone invited you to a private Gather room — synced playback, a call and a chat.',
};

/** Guest join landing: /join/<inviteCode>. */
export default async function JoinPage({ params }: { params: Promise<{ code: string }> }) {
  const { code } = await params;
  return <JoinClient code={code as InviteCode} />;
}
